config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"

  get '@:username', to: 'users#username'
  post 'users/follow', to: 'users#follow'
  delete 'users/unfollow', to: 'users#unfollow'
  post 'like', to: 'likes#like'
  delete 'dislike', to: 'likes#dislike'
  get 'bookmarks', to: 'bookmarks#index'
  post 'bookmarks', to: 'bookmarks#create'
  delete 'bookmarks', to: 'bookmarks#destroy'
  get 'feed', to: 'articles#index'

  resources :comments, only: [:create, :edit, :update]
  resource :contacts, only: [:new, :create], path_names: { :new => '' }

  resources :users, only: [:show, :index] do
    resource :wall, only: [:create] do
      resources :articles, only: [:create]
    end
    get 'friends', to: 'users#friends'
    get 'subscriptions', to: 'users#subscriptions'
    get 'followers', to: 'users#followers'
  end

  resources :articles, except: [:new]
  resource :wall, only: [:create]
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 4000 }
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :bookmarks, as: :bookmarkable
  has_many :likes, as: :likeable, dependent: :destroy

  def self.comments_find(commentable_type, commentable_id)
    Comment.where('commentable_type = ? and commentable_id = ? and parent_id = 0',
                  commentable_type, commentable_id).order('id ASC')
  end

  def self.replies_find(commentable_type, commentable_id)
    Comment.where('commentable_type = ? and commentable_id = ? and parent_id != 0',
                  commentable_type, commentable_id).order('id ASC')
           .group_by { |comment| comment['parent_id'] }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def edit
    @comment = Comment.find(params[:id])

    if current_user.id != @comment.user_id
      redirect_to @comment, alert: 'Этот комментарий принадлежит другому пользователю, ' \
                                   'только он может его редактировать.'
    end
  end

  def create
    commentable = correct_instance(params)
    @comment = commentable.comments.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      new_comment = polymorphic_path(commentable).concat("#comment_#{@comment.id}")
      redirect_to new_comment, notice: 'Комментарий успешно добавлен'
    end
  end

  def update
    @comment = Comment.find(params[:id])

    if current_user.id != @comment.user_id
      return redirect_to @comment, alert: 'Этот комментарий принадлежит другому пользователю, ' \
                                          'только он может его редактировать.'
    end

    if @comment.update(comment_update_params)
      redirect_to polymorphic_path(@comment.commentable).concat("#comment_#{@comment.id}")
    else
      render action: 'edit'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end

  def comment_update_params
    params.require(:comment).permit(:body)
  end

  def correct_instance(params)
    klass = Kernel.const_get(params[:comment][:type].to_sym)
    id = params[:comment][:type_id]
    klass.find(id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_button.html.erb
<% comments_count = commentable.comments.size %>
<% if current_user %>
  <% comment_from_current_user = current_user.comments.find_by(commentable: commentable) %>
<% else %>
  <% comment_from_current_user = nil %>
<% end %>

<%= link_to article_path(commentable, anchor: 'comments'),
            class: 'btn btn-outline-primary', data: { turbo: false } do %>
  <% if comment_from_current_user.nil? %>
    <i class="bi bi-chat-left"></i>
  <% else %>
    <i class="bi bi-chat-left-fill"></i>
  <% end %>
    <span class="fw-bold"><%= comments_count if comments_count.positive? %></span>
<% end %>

app/views/comments/_child_comment.html.erb
<div class="d-flex mt-4" id="<%= dom_id(comment) %>">
  <div class="flex-shrink-0">
    <%= link_to comment.user do %>
      <%= image_tag user_avatar(comment.user, 100),
                    class: 'rounded-circle border border-secondary',
                    size: '40x40' %>
      <%= render partial: 'comments/dropdown',
                 locals: { comment: comment } %>
    <% end %>
  </div>

  <div class="ms-3">
    <div class="fw-semibold">
      <%= link_to comment.user.full_name, comment.user,
                  class: 'text-decoration-none', data: { turbo: false } %>
    </div>

    <div><%= comment.body %></div>

    <div class="row">
      <%= render partial: 'comments/time', locals: { comment: comment } %>
      <%= render partial: 'likes/button', locals: { likeable: comment } %>
    </div>
  </div>
</div>

app/views/comments/_dropdown.html.erb
<div class="col dropdown dropdown-menu-end text-center">
  <a href="#" class="d-block link-dark" data-bs-toggle="dropdown">
    <i class="bi bi-three-dots" style="font-size: 1.4rem"></i>
  </a>
  <ul class="dropdown-menu text-small">
    <% if user_signed_in? && current_user.id == comment.user_id %>
      <li>
        <%= link_to 'Редактировать', edit_comment_path(comment),
                    class: 'dropdown-item', data: { turbo: false } %>
      </li>
    <% end %>

    <li>
      <%= render partial: 'bookmarks/button', locals: { bookmarkable: comment } %>
    </li>
  </ul>
</div>

app/views/comments/_form.html.erb
<%= form_with model: instance.comments.new, data: {turbo: false} do |form| %>
  <form>
    <div class="mb-2 mt-2">
      <%= form.text_area :body, rows: "2", cols: 'auto', class: 'form-control',
                         placeholder: 'Написать комментарий...' %>
    </div>
    <div class="mb-4">
      <%= form.hidden_field :type, value: instance.class %>
      <%= form.hidden_field :type_id, value: instance.id %>
      <%= form.hidden_field :parent_id, value: parent_id ||= 0 %>
      <%= form.submit 'Отправить', class: 'btn btn-outline-primary' %>
    </div>
  </form>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <div class="d-flex mb-2" id="<%= dom_id(comment) %>">
    <div class="flex-shrink-0">
      <%= link_to comment.user do %>
        <%= image_tag user_avatar(comment.user, 100),
                      class: 'rounded-circle border border-secondary',
                      size: '40x40' %>
      <% end %>
      <%= render partial: 'comments/dropdown',
                 locals: { comment: comment } %>
    </div>

    <div class="row ms-3">
      <div class="fw-semibold my-0">
        <%= link_to comment.user.full_name, comment.user,
                    class: 'text-decoration-none', data: { turbo: false } %>
      </div>

      <%= simple_format(comment.body, {}, wrapper_tag: "div") %>

      <div class="row">
        <%= render partial: 'comments/time', locals: { comment: comment } %>
        <%= render partial: 'likes/button', locals: { likeable: comment } %>
      </div>

      <% if @replies.key?(comment.id) %>
        <% @replies[comment.id].each do |reply| %>
          <%= render partial: 'comments/child_comment', locals: { comment: reply } %>
        <% end %>
      <% end %>

      <!-- Reply form -->
      <div>
        <a class="text-decoration-none"
           onclick="reply_form_<%= comment.id %>.style.display='block'"
           style="cursor: pointer">Ответить</a>

        <div id="reply_form_<%= comment.id %>" style="display: none">
          <%= render partial: 'comments/form',
                     locals: { instance: @article, parent_id: comment.id } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_index_separate.html.erb
<% comments.each do |comment| %>
  <div class="card mb-3 shadow-sm border" style="border-radius: 13px;">
    <div class="card-body">
      <div class="my-0">
        <div class="row">
          <div class="col-auto pe-0">
            <div class="d-flex mb-2" id="<%= dom_id(comment) %>">
              <!-- Parent comment-->
              <div class="flex-shrink-0">
                <%= link_to comment.user do %>
                  <%= image_tag user_avatar(comment.user, 100),
                                class: 'rounded-circle border border-secondary',
                                size: '40x40' %>
                <% end %>

                <%= render partial: 'comments/dropdown',
                           locals: { comment: comment } %>
              </div>

              <div class="row ms-3">
                <div class="fw-semibold my-0">
                  <%= link_to comment.user.full_name, comment.user,
                              class: 'text-decoration-none', data: { turbo: false } %>
                </div>

                <%= simple_format(comment.body, {}, wrapper_tag: "div") %>

                <div class="row">
                  <%= render partial: 'comments/time', locals: { comment: comment } %>
                  <%= render partial: 'likes/button', locals: { likeable: comment } %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_show.html.erb
<% comments.each do |comment| %>
  <!-- Comment -->
  <div class="d-flex mb-2" id="<%= dom_id(comment) %>">
    <!-- Parent comment-->
    <div class="flex-shrink-0">
      <%= link_to comment.user do %>
        <%= image_tag user_avatar(comment.user, 100),
                      class: 'rounded-circle border border-secondary', size: '40x40' %>
      <% end %>
    </div>

    <div class="ms-3">
      <div class="fw-semibold my-0">
        <%= link_to comment.user.full_name, comment.user,
                    class: 'text-decoration-none', data: { turbo: false } %>
      </div>

      <div><%= comment.body %></div>

      <small class="text-muted">
        <%= l(comment.created_at, format: :post_short) %>
      </small>

      <% if @replies.key?(comment.id) %>
        <% @replies[comment.id].each do |reply| %>
          <!-- Child comment -->
          <div class="d-flex mt-4" id="<%= dom_id(reply) %>">
            <div class="flex-shrink-0">
              <%= link_to reply.user do %>
                <%= image_tag user_avatar(reply.user, 100),
                              class: 'rounded-circle border border-secondary', size: '40x40' %>
              <% end %>
            </div>

            <div class="ms-3">
              <div class="fw-semibold">
                <%= link_to reply.user.full_name, reply.user,
                            class: 'text-decoration-none', data: { turbo: false } %>
              </div>

              <div><%= reply.body %></div>

              <small class="text-muted">
                <%= l(reply.created_at, format: :post_short) %>
              </small>
            </div>
          </div>
        <% end %>
      <% end %>

      <!-- Reply form -->
      <div>
        <a class="text-decoration-none"
           onclick="reply_form_<%= comment.id %>.style.display='block'"
           style="cursor: pointer">Ответить</a>

        <div id="reply_form_<%= comment.id %>" style="display: none">
          <%= render partial: 'comments/form',
                     locals: { instance: @article, parent_id: comment.id } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_time.html.erb
<div class="col-auto">
  <% comment.created_at.year == Date.today.year ? format = :post_short : format = :date %>
  <% time = l(comment.created_at, format: format) %>
  <% comment_link = polymorphic_path(comment.commentable)
                      .concat("#comment_#{comment.id}") %>
  <%= link_to time, comment_link,
              class: 'text-decoration-none text-muted',
              data: { turbo: false } %>
</div>

app/views/comments/_time_link.html.erb
<div class="col">
  <% time = l(comment.created_at, format: :post_short) %>
  <% comment_link = polymorphic_path(comment.commentable)
                      .concat("#comment_#{comment.id}") %>
  <%= link_to time, comment_link,
              class: 'text-decoration-none text-muted',
              data: { turbo: false } %>
</div>

app/views/comments/edit.html.erb
<%= form_for :comment, url: comment_path(@comment), method: :patch,
             data: { turbo: false } do |f| %>
  <div class="card mb-3 shadow-sm border" style="border-radius: 13px;">
    <div class="card-body">
      <h4>Редактирование комментария</h4>
      <form>
        <div class="mb-2 mt-2">
          <%= f.label :body, 'Текст', class: "form-label" %>
          <%= f.text_area :body, size: '40x5',
                          placeholder: 'Написать комментарий...',
                          class: 'form-control' %>
        </div>
        <div class="mb-1">
          <%= f.submit 'Сохранить', class: 'btn btn-outline-primary' %>
        </div>
      </form>
    </div>
  </div>
<% end %>