config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"

  get '@:username', to: 'users#username'
  post 'users/follow', to: 'users#follow'
  delete 'users/unfollow', to: 'users#unfollow'
  post 'like', to: 'likes#like'
  delete 'dislike', to: 'likes#dislike'
  get 'bookmarks', to: 'bookmarks#index'
  post 'bookmarks', to: 'bookmarks#create'
  delete 'bookmarks', to: 'bookmarks#destroy'
  get 'feed', to: 'articles#index'

  resources :comments, only: [:create, :edit, :update]
  resource :contacts, only: [:new, :create], path_names: { :new => '' }

  resources :users, only: [:show, :index] do
    resource :wall, only: [:create] do
      resources :articles, only: [:create]
    end
    get 'friends', to: 'users#friends'
    get 'subscriptions', to: 'users#subscriptions'
    get 'followers', to: 'users#followers'
  end

  resources :articles, except: [:new]
  resource :wall, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :comments
  has_many :likes
  has_many :own_bookmarks, class_name: 'Bookmark'
  has_many :bookmarks, as: :bookmarkable
  has_one :wall, as: :wallable
  has_one_attached :avatar

  has_many :followed_users,
           foreign_key: :follower_id,
           class_name: 'Relationship',
           dependent: :destroy

  has_many :followees,
           through: :followed_users,
           dependent: :destroy

  has_many :following_users,
           foreign_key: :followee_id,
           class_name: 'Relationship',
           dependent: :destroy

  has_many :followers,
           through: :following_users,
           dependent: :destroy

  validates :username, uniqueness: true, format: { with: /\A[a-zA-Z]*\z/ },
                       length: { maximum: 32 }, allow_blank: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :avatar, content_type: ['image/png', 'image/jpeg'],
                     size: { less_than: 1.megabyte }

  after_create do
    create_wall
  end

  def self.ransackable_attributes(_auth_object = nil)
    ['email', 'first_name', 'last_name', 'username']
  end

  def self.ransackable_associations(_auth_object = nil)
    ['avatar_attachment', 'avatar_blob']
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  before_action :authenticate_user!, only: [:friends, :follow, :unfollow]

  def index
    @q = User.ransack(params[:q])
    @result = @q.result
    @users = @result.order('id ASC').page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.wall.articles.where.not(id: nil).order('id desc').page(params[:page])
  end

  def username
    @user = User.find_by(username: params[:username])
    @articles = @user.wall.articles.where.not(id: nil).order('id desc').page(params[:page])
    render 'show'
  end

  def friends
    @user = User.find(params[:user_id])
    @friends = @user.followees & @user.followers
    @count = @friends.size
    @users = Kaminari.paginate_array(@friends).page(params[:page])
    render 'users/relationships', locals: { name: 'Друзья' }
  end

  def followers
    @user = User.find(params[:user_id])
    @friends = @user.followees & @user.followers
    @followers = @user.followers - @friends
    @count = @followers.size
    @users = Kaminari.paginate_array(@followers).page(params[:page])
    render 'users/relationships', locals: { name: 'Подписчики' }
  end

  def subscriptions
    @user = User.find(params[:user_id])
    @friends = @user.followees & @user.followers
    @subscriptions = @user.followees - @friends
    @count = @subscriptions.size
    @users = Kaminari.paginate_array(@subscriptions).page(params[:page])
    render 'users/relationships', locals: { name: 'Подписки' }
  end

  def follow
    @user = User.find(params[:id])
    Relationship.create_or_find_by(follower_id: current_user.id,
                                   followee_id: @user.id)
    update_counters_and_button
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.followed_users.where(follower_id: current_user.id,
                                      followee_id: @user.id).destroy_all
    update_counters_and_button
  end
end

app/helpers/users_helper.rb
module UsersHelper
  include ActionView::RecordIdentifier

  def following?(user)
    current_user&.followees&.include?(user)
  end

  def update_counters_and_button
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("user_#{@user.id}_follow_button",
                               partial: 'users/follow_button',
                               locals: { user: @user }),
          turbo_stream.update("user_#{@user.id}_friend_count",
                              partial: 'users/friend_count',
                              locals: { user: @user }),
          turbo_stream.update("user_#{@user.id}_subscription_count",
                              partial: 'users/subscription_count',
                              locals: { user: @user }),
          turbo_stream.update("user_#{@user.id}_follower_count",
                              partial: 'users/follower_count',
                              locals: { user: @user })
        ]
      end
    end
  end
end

app/views/users/_dropdown.html.erb
<div class="col-auto dropdown text-end dropdown-menu-end">
  <a href="#" class="d-block link-dark" data-bs-toggle="dropdown">
    <i class="bi bi-three-dots" style="font-size: 1.4rem"></i>
  </a>
  <ul class="dropdown-menu text-small">
    <% if current_user == user %>
      <li>
        <%= link_to 'Редактировать профиль', edit_user_registration_path,
                    class: 'dropdown-item', data: { turbo: false } %>
      </li>
    <% else %>
      <li>
        <%= render partial: 'bookmarks/button', locals: { bookmarkable: user } %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/_follow_button.html.erb
<%= turbo_frame_tag "user_#{user.id}_follow_button" do %>
  <% if !user_signed_in? %>
    <%= link_to 'Добавить в друзья', new_user_session_path,
                class: 'btn btn-sm btn-outline-success',
                data: { turbo: false } %>
  <% elsif following?(user) %>
    <%= button_to 'Удалить из друзей', users_unfollow_path(id: user.id),
                  method: :delete, class: 'btn btn-sm btn-outline-danger' %>
  <% else %>
    <%= button_to 'Добавить в друзья', users_follow_path(id: user.id),
                  method: :post, class: 'btn btn-sm btn-outline-success' %>
  <% end %>
<% end %>

app/views/users/_follower_count.html.erb
<%= turbo_frame_tag "user_#{user.id}_follower_count" do %>
  <% friends = user.followees & user.followers %>
  <%= follower_count = user.followers.size - friends.size %>
<% end %>

app/views/users/_friend_count.html.erb
<%= turbo_frame_tag "user_#{user.id}_friend_count" do %>
  <%= friend_count = (user.followees & user.followers).size %>
<% end %>

app/views/users/_search_form.html.erb
<%= form_with url: users_path, method: :get, data: { turbo: false } do %>
  <% search_params = :first_name_or_last_name_or_username_or_email_cont  %>
  <% search_field :q, search_params,
                  class: 'form-control form-control-sm', placeholder: 'Поиск',
                  style: "background-color: #edeef0" %>
<% end %>

app/views/users/_search_result.html.erb
<% users.each do |user| %>
  <div class="card-body">
    <div class="my-0">
      <div class="row">
        <div class="col-auto pe-0">
          <%= link_to user do %>
            <%= image_tag user_avatar(user, 200),
                          class: 'rounded-circle border border-secondary',
                          size: '80x80' %>
          <% end %>
        </div>

        <div class="col">
          <h6 class="my-0">
            <%= link_to user.full_name, user,
                        class: 'card-title text-decoration-none',
                        data: { turbo: false } %>
          </h6>

          <span class="text-muted"><%= user.email %></span>
        </div>

        <div class="col">
          <% if current_user != user %>
            <%= render 'users/follow_button', user: user %>
          <% end %>
        </div>

        <%= render partial: 'users/dropdown', locals: { user: user } %>
      </div>
    </div>
  </div>
<% end %>

<% if users.blank? %>
  <div class="card-body">
    <h5>Ничего не найдено</h5>
  </div>
<% end %>

app/views/users/_subscription_count.html.erb
<%= turbo_frame_tag "user_#{user.id}_subscription_count" do %>
  <% friends = user.followees & user.followers %>
  <%= subscription_count = user.followees.size - friends.size %>
<% end %>

app/views/users/index.html.erb
<div class="card mb-3 shadow-sm border" style="border-radius: 13px;">
  <div class="card-body pb-0">
    <h5>
      <span>Результаты поиска</span>
      <span class="text-muted ms-1"><%= @result.size %></span>
    </h5>
  </div>
  <%= render partial: 'users/search_result', locals: { users: @users } %>
</div>

<%= paginate @users %>

app/views/users/relationships.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="card mb-3 shadow-sm border" style="border-radius: 13px;">
      <div class="card-body pb-0">
        <h5>
          <span><%= name %></span>
          <span class="text-muted ms-1"><%= @count %></span>
        </h5>
      </div>
      <%= render partial: 'users/search_result', locals: { users: @users } %>
    </div>

    <%= paginate @users %>
  </div>

  <div class="col-md-4">
    <div class="card mb-3 shadow-sm border" style="border-radius: 13px;">
      <div class="card-body">
        <div class="list-group">

          <%= link_to @user,
                      class: "list-group-item-action p-0 text-decoration-none py-1 text-dark rounded",
                      data: {turbo: false} do %>
            <div class="row">
                <div class="col-auto pe-0">
                  <%= image_tag user_avatar(@user, 100),
                                  class: 'my-auto rounded-circle border border-secondary',
                                  size: '45x45' %>
                </div>
              <div class="col-auto">
                  <span class="nav-link-text"><%= @user.full_name %></span><br>
                  <small class="text-muted">перейти к странице</small>
              </div>
              </div>
          <% end %>

          <%= link_to user_friends_path(@user),
                      class: "list-group-item-action p-0 text-decoration-none py-1 text-dark rounded",
                      data: {turbo: false} do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-text">Друзья</span>
            </div>
          <% end %>

          <%= link_to user_subscriptions_path(@user),
                      class: "list-group-item-action p-0 text-decoration-none py-1 text-dark rounded",
                      data: {turbo: false} do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-text">Подписки</span>
            </div>
          <% end %>

          <%= link_to user_followers_path(@user),
                      class: "list-group-item-action p-0 text-decoration-none py-1 text-dark rounded",
                      data: {turbo: false} do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-text">Подписчики</span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="card mb-3 shadow-sm border" style="border-radius: 13px;">
  <div class="card-body">
      <div class="mb-2 mt-2">
        <div class="row">
          <div class="col-md-3 mb-2">
            <%= image_tag user_avatar(@user, 400), class: 'img-thumbnail' %>
          </div>
          <div class="col-auto">
            <div class="row">
              <div class="col-auto">
                <h4><%= @user.full_name %></h4>
              </div>

              <%= render partial: 'users/dropdown', locals: { user: @user } %>
            </div>

            <hr>
            <div>
              <b>Почта: </b><%= @user.email %><br/>
              <% if @user.username.present? %>
                <b>Никнейм: </b>
                <%= link_to "@#{@user.username}", "#{root_url}@#{@user.username}",
                           class: 'text-decoration-none', data: { turbo: false } %><br/>
              <% end %>
              <b>Дата регистрации: </b><%= l(@user.created_at, format: :long) %><br/>
              <b><%= link_to 'Друзья:', user_friends_path(@user),
                             class: 'text-decoration-none text-reset',
                             data: { turbo: false } %></b>
              <%= render 'users/friend_count', user: @user %><br/>

              <b><%= link_to 'Подписки:', user_subscriptions_path(@user),
                             class: 'text-decoration-none text-reset',
                             data: { turbo: false } %></b>
              <%= render 'users/subscription_count', user: @user %><br/>

              <b><%= link_to 'Подписчики:', user_followers_path(@user),
                             class: 'text-decoration-none text-reset',
                             data: { turbo: false } %></b>
              <%= render 'users/follower_count', user: @user %><br/>

              <% if current_user != @user %>
                <%= render 'users/follow_button', user: @user %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

<% if user_signed_in? %>
  <%= render partial: 'articles/form', locals: { wallable: @user } %>
<% end %>

<%= render partial: 'articles/content',
           locals: { articles: @articles } %>

<%= paginate @articles %>