config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"

  get '@:username', to: 'users#username'
  post 'users/follow', to: 'users#follow'
  delete 'users/unfollow', to: 'users#unfollow'
  post 'like', to: 'likes#like'
  delete 'dislike', to: 'likes#dislike'
  get 'bookmarks', to: 'bookmarks#index'
  post 'bookmarks', to: 'bookmarks#create'
  delete 'bookmarks', to: 'bookmarks#destroy'
  get 'feed', to: 'articles#index'

  resources :comments, only: [:create, :edit, :update]
  resource :contacts, only: [:new, :create], path_names: { :new => '' }

  resources :users, only: [:show, :index] do
    resource :wall, only: [:create] do
      resources :articles, only: [:create]
    end
    get 'friends', to: 'users#friends'
    get 'subscriptions', to: 'users#subscriptions'
    get 'followers', to: 'users#followers'
  end

  resources :articles, except: [:new]
  resource :wall, only: [:create]
end

app/views/layouts/_footer.html.erb
<div class="row mx-auto">
  <div class="container">
    <div class="container px-0">
        <footer class="py-3 border-top">
          <a class="text-decoration-none text-muted" href="https://github.com/vladkostikov/socialist">
            © 2023 Vladislav Kostikov
          </a>
        </footer>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid mb-4 bg-white mx-auto">
  <header class="container px-0 py-1 d-flex flex-wrap align-items-center justify-content-center">
    <ul class="nav col-md-2">
      <%= link_to root_path, data: { turbo: false } do %>
        <%= image_tag 'logo.svg', class: 'pe-5', size: '200x38' %>
      <% end %>
    </ul>

    <ul class="nav me-auto">
      <li><%= render partial: 'users/search_form' %></li>
    </ul>

    <div class="col-auto text-end">
      <% if user_signed_in? %>
        <div class="dropdown text-end dropdown-menu-end">
          <a href=""
             class="d-block link-dark text-decoration-none dropdown-toggle"
             data-bs-toggle="dropdown"
             aria-expanded="false"
             role="button">
            <%= image_tag user_avatar(current_user, 100),
                          class: 'rounded-circle', size: '32x32' %>
          </a>
          <ul class="dropdown-menu text-small">
            <li><%= link_to 'Профиль', current_user,
                          class: 'dropdown-item', data: { turbo: false } %></li>

            <li><%= link_to 'Настройки', edit_user_registration_path,
                          class: 'dropdown-item', data: { turbo: false } %></li>

            <li><hr class="dropdown-divider"></li>

            <li><%= link_to 'Выйти', destroy_user_session_path,
                          class: 'dropdown-item text-danger',
                          data: { turbo_method: :delete,
                                  turbo_confirm: 'Вы точно хотите выйти?'} %>
            </li>
          </ul>
        </div>
      <% else %>
        <%= link_to 'Вход', new_user_session_path,
                    class: 'btn btn-outline-primary me-0' %>
        <%= link_to 'Регистрация', new_user_registration_path,
                    class: 'btn btn-outline-success me-0' %>
      <% end %>
    </div>
  </header>
</div>

app/views/layouts/_left_sidebar.html.erb
<div class="list-group me-1 pt-1">
  <%= link_to current_user || new_user_session_path,
              class: "list-group-item-action p-0 text-decoration-none py-1 text-dark rounded",
              data: {turbo: false} do %>
    <div class="d-flex align-items-center">
      <i class="bi bi-person-circle me-1" style="color: #447bba"></i>
      <span class="nav-link-text">Моя страница</span>
    </div>
  <% end %>

  <%= link_to feed_path,
              class: "list-group-item-action p-0 text-decoration-none py-1 text-dark rounded",
              data: {turbo: false} do %>
    <div class="d-flex align-items-center">
      <i class="bi bi-file-post me-1" style="color: #447bba"></i>
      <span class="nav-link-text">Новости</span>
    </div>
  <% end %>

  <% if current_user %>
    <% friends_path = user_friends_path(current_user) %>
  <% else %>
    <% friends_path = new_user_session_path %>
  <% end %>
  <%= link_to friends_path,
              class: "list-group-item-action p-0 text-decoration-none py-1 text-dark rounded",
              data: {turbo: false} do %>
    <div class="d-flex align-items-center">
      <i class="bi bi-people-fill me-1" style="color: #447bba"></i>
      <span class="nav-link-text">Друзья</span>
    </div>
  <% end %>

  <%= link_to bookmarks_path,
              class: "list-group-item-action p-0 text-decoration-none py-1 text-dark rounded",
              data: {turbo: false} do %>
    <div class="d-flex align-items-center">
      <i class="bi bi-bookmark-fill me-1" style="color: #447bba"></i>
      <span class="nav-link-text">Закладки</span>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">

    <title>SociaList – социальная сеть</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  </head>

  <body style="background: #edeef0">
    <%= render 'layouts/header' %>

    <div class="row mx-auto">
      <div class="container">
        <div class="container">
          <div class="row">
            <div class="col-md-2 ps-0 pe-0 mb-3">
              <%= render 'layouts/left_sidebar' %>
            </div>

            <div class="col-md-10 ps-0 pe-0">
              <% if notice %>
                <div class="alert alert-info"><%= notice %></div>
              <% end %>

              <% if alert %>
                <div class="alert alert-danger"><%= alert %></div>
              <% end %>

              <%= yield %>
            </div>
          </div>

        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>